import { theme } from 'antd';
import type { ThemeConfig } from 'antd';
import { uiPalette } from '../styles/palette';

const { brand, semantic, surface, text } = uiPalette;

export const appTheme: ThemeConfig = {
  algorithm: theme.defaultAlgorithm,
  token: {
    colorPrimary: brand.primary,
    colorPrimaryHover: brand.hover,
    colorPrimaryActive: brand.active,
    colorPrimaryBg: brand.soft,
    colorPrimaryBgHover: brand.softHover,
    colorPrimaryBorder: brand.border,
    colorPrimaryBorderHover: brand.primary,

    colorSuccess: semantic.success,
    colorWarning: semantic.warning,
    colorError: semantic.danger,
    colorInfo: semantic.info,

    colorBgLayout: surface.page,
    colorBgContainer: surface.card,
    colorBgElevated: surface.elevated,
    colorBgSpotlight: '#35435e',
    colorFillSecondary: surface.muted,
    colorFillTertiary: '#f2f6fc',
    colorFillQuaternary: surface.borderSubtle,

    colorBorder: surface.border,
    colorBorderSecondary: surface.borderSubtle,
    colorSplit: surface.borderSubtle,

    colorText: text.primary,
    colorTextSecondary: text.secondary,
    colorTextTertiary: text.tertiary,
    colorTextQuaternary: text.muted,
    colorTextPlaceholder: text.muted,
    colorTextDisabled: '#a7b1c2',
    colorTextHeading: text.heading,
    colorTextLabel: text.secondary,
    colorTextDescription: text.tertiary,

    fontFamily: '"Segoe UI Variable Text", "Segoe UI Variable", "Segoe UI", system-ui, -apple-system, BlinkMacSystemFont, sans-serif',
    fontSize: 14,
    fontWeightStrong: 620,
    fontSizeSM: 12.5,
    fontSizeLG: 15.5,
    fontSizeXL: 18,
    fontSizeHeading1: 27,
    fontSizeHeading2: 21,
    fontSizeHeading3: 18,
    fontSizeHeading4: 15,
    fontSizeHeading5: 14,
    lineHeight: 1.55,
    lineHeightHeading1: 1.24,
    lineHeightHeading2: 1.28,
    lineHeightHeading3: 1.34,

    borderRadius: 11,
    borderRadiusLG: 16,
    borderRadiusSM: 9,
    borderRadiusXS: 7,
    borderRadiusOuter: 16,

    controlHeight: 40,
    controlHeightSM: 34,
    controlHeightLG: 46,
    controlOutlineWidth: 2,
    controlOutline: 'rgba(112, 105, 232, 0.16)',

    boxShadow: '0 1px 2px rgba(63, 78, 122, 0.025), 0 10px 30px rgba(70, 86, 139, 0.055)',
    boxShadowSecondary: '0 18px 44px rgba(50, 63, 103, 0.14)',
    boxShadowTertiary: '0 0 0 3px rgba(112, 105, 232, 0.085)',

    padding: 16,
    paddingLG: 20,
    paddingXL: 24,
    paddingSM: 12,
    paddingXS: 8,
    paddingXXS: 4,
    margin: 16,
    marginLG: 20,
    marginXL: 24,
    marginSM: 12,
    marginXS: 8,
    marginXXS: 4,

    motionUnit: 0.04,
    motionBase: 0,
    motionEaseInOut: 'cubic-bezier(0.4, 0, 0.2, 1)',
    motionEaseOut: 'cubic-bezier(0, 0, 0.2, 1)',
    motionEaseOutBack: 'cubic-bezier(0, 0, 0.2, 1)',
  },
  components: {
    Button: {
      borderRadius: 11,
      borderRadiusSM: 9,
      borderRadiusLG: 14,
      controlHeight: 40,
      controlHeightSM: 34,
      controlHeightLG: 46,
      fontWeight: 580,
      paddingInline: 16,
      paddingInlineSM: 12,
      paddingInlineLG: 20,
      primaryShadow: 'none',
      defaultShadow: 'none',
      dangerShadow: 'none',
    },
    Card: {
      borderRadiusLG: 16,
      headerFontSize: 15,
      headerFontSizeSM: 14,
      paddingLG: 20,
      headerHeight: 52,
      colorBorderSecondary: surface.borderSubtle,
    },
    Drawer: {
      borderRadiusLG: 16,
      paddingLG: 20,
      footerPaddingBlock: 12,
      footerPaddingInline: 20,
    },
    Form: {
      labelFontSize: 13,
      labelColor: text.secondary,
      itemMarginBottom: 18,
      verticalLabelPadding: '0 0 7px',
    },
    Input: {
      controlHeight: 40,
      controlHeightSM: 34,
      controlHeightLG: 46,
      borderRadius: 11,
      borderRadiusLG: 14,
      borderRadiusSM: 9,
      paddingInline: 12,
      paddingInlineSM: 10,
      paddingInlineLG: 14,
    },
    InputNumber: {
      controlHeight: 40,
      controlHeightSM: 34,
      controlHeightLG: 46,
      borderRadius: 11,
      paddingInline: 10,
    },
    Modal: {
      borderRadiusLG: 16,
      paddingLG: 20,
      paddingMD: 18,
      paddingContentHorizontalLG: 20,
      footerBg: surface.card,
    },
    Pagination: {
      itemSize: 34,
      borderRadius: 8,
      fontWeightStrong: 600,
    },
    Select: {
      controlHeight: 40,
      controlHeightSM: 34,
      controlHeightLG: 46,
      borderRadius: 11,
      borderRadiusLG: 14,
      borderRadiusSM: 9,
    },
    Table: {
      headerBg: '#f5f8fd',
      headerColor: text.secondary,
      headerSplitColor: 'transparent',
      bodySortBg: 'transparent',
      headerSortActiveBg: '#f0f0fa',
      headerSortHoverBg: '#f4f4fb',
      rowHoverBg: '#f7f9fd',
      rowSelectedBg: brand.soft,
      rowSelectedHoverBg: brand.softHover,
      borderColor: surface.borderSubtle,
      borderRadiusLG: 14,
      cellPaddingBlock: 13,
      cellPaddingInline: 15,
      cellPaddingBlockSM: 9,
      cellPaddingInlineSM: 11,
    },
    Tag: {
      borderRadiusSM: 9,
    },
    Menu: {
      itemBorderRadius: 11,
      itemHeight: 40,
      itemMarginInline: 0,
      itemMarginBlock: 1,
      itemPaddingInline: 12,
      groupTitleFontSize: 11,
      subMenuItemBg: 'transparent',
    },
    Dropdown: {
      borderRadius: 11,
      borderRadiusLG: 14,
      paddingBlock: 5,
    },
    Segmented: {
      borderRadius: 11,
      borderRadiusLG: 14,
      borderRadiusSM: 9,
      itemSelectedBg: surface.card,
      trackBg: '#f1f4fa',
      trackPadding: 3,
    },
    Tabs: {
      borderRadius: 8,
      cardBg: surface.muted,
      itemSelectedColor: brand.primary,
      inkBarColor: brand.primary,
      itemHoverColor: brand.hover,
      titleFontSize: 14,
    },
    Progress: {
      lineBorderRadius: 6,
    },
    Alert: {
      borderRadius: 11,
      borderRadiusLG: 14,
    },
    Badge: {
      colorBgContainer: surface.card,
    },
    Avatar: {
      borderRadius: 11,
      borderRadiusLG: 14,
      borderRadiusSM: 9,
    },
    Statistic: {
      titleFontSize: 13,
    },
    Timeline: {
      itemPaddingBottom: 18,
    },
    DatePicker: {
      controlHeight: 40,
      controlHeightSM: 34,
      controlHeightLG: 46,
      borderRadius: 11,
      paddingInline: 12,
    },
    Descriptions: {
      contentColor: text.primary,
      labelBg: surface.muted,
      labelColor: text.secondary,
      borderRadius: 11,
      borderRadiusLG: 14,
    },
    List: {
      colorSplit: surface.borderSubtle,
    },
  },
};
