package com.example.dms.sales;
import com.example.dms.audit.AuditService;import com.example.dms.common.*;import com.example.dms.customer.*;import com.example.dms.debt.*;import com.example.dms.inventory.*;import com.example.dms.notification.*;import com.example.dms.product.*;import jakarta.validation.constraints.*;import lombok.*;import org.springframework.cache.annotation.CacheEvict;import org.springframework.data.domain.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;import java.math.*;import java.time.*;import java.util.*;
@RestController @RequestMapping("/api/sales-orders") @RequiredArgsConstructor
public class SalesOrderController {
 private final SalesOrderRepository orders; private final ProductRepository products; private final CustomerRepository customers; private final InventoryService inventory; private final CustomerDebtRepository debts; private final AuditService audit; private final NotificationProducer notifications;
 public record Item(Long productId,Integer quantity,BigDecimal discountAmount){} public record CreateOrder(Long customerId,Long warehouseId,BigDecimal paidAmount,List<Item> items){}
 @GetMapping @PreAuthorize("hasAuthority('SALES_ORDER_CREATE')") ApiResponse<?> list(@RequestParam(defaultValue="0")int page){return ApiResponse.ok(orders.findByTenantIdOrderByCreatedAtDesc(TenantContext.tenantRequired(),PageRequest.of(page,20)));}
 @PostMapping @PreAuthorize("hasAuthority('SALES_ORDER_CREATE')") @Transactional ApiResponse<?> create(@RequestBody CreateOrder r){Long t=TenantContext.tenantRequired();customers.findByIdAndTenantIdAndDeletedAtIsNull(r.customerId(),t).orElseThrow(()->new BusinessException("Customer not found"));SalesOrder o=SalesOrder.builder().tenantId(t).customerId(r.customerId()).warehouseId(r.warehouseId()).code("SO-"+t+"-"+(orders.countByTenantId(t)+1)).status("DRAFT").paidAmount(r.paidAmount()==null?BigDecimal.ZERO:r.paidAmount()).totalAmount(BigDecimal.ZERO).debtAmount(BigDecimal.ZERO).items(new ArrayList<>()).build();BigDecimal total=BigDecimal.ZERO;for(Item it:r.items()){Product p=products.findByIdAndTenantIdAndDeletedAtIsNull(it.productId(),t).orElseThrow(()->new BusinessException("Product not found"));BigDecimal discount=it.discountAmount()==null?BigDecimal.ZERO:it.discountAmount();BigDecimal line=p.getSellingPrice().multiply(BigDecimal.valueOf(it.quantity())).subtract(discount);SalesOrderItem item=SalesOrderItem.builder().order(o).productId(p.getId()).quantity(it.quantity()).unitPrice(p.getSellingPrice()).discountAmount(discount).lineTotal(line).build();o.getItems().add(item);total=total.add(line);}if(o.getPaidAmount().compareTo(total)>0)throw new BusinessException("Paid exceeds total");o.setTotalAmount(total);o.setDebtAmount(total.subtract(o.getPaidAmount()));orders.save(o);audit.log("SALES_ORDER_CREATED","SalesOrder",o.getId(),o.getCode());return ApiResponse.ok(o);}
 @PostMapping("/{id}/confirm") @PreAuthorize("hasAuthority('SALES_ORDER_CONFIRM')") @Transactional @CacheEvict(value="dashboard",allEntries=true) ApiResponse<?> confirm(@PathVariable Long id){Long t=TenantContext.tenantRequired();SalesOrder o=orders.findByIdAndTenantId(id,t).orElseThrow(()->new BusinessException("Order not found"));if(!"DRAFT".equals(o.getStatus()))throw new BusinessException("Only DRAFT can be confirmed");for(SalesOrderItem i:o.getItems())inventory.deduct(t,o.getWarehouseId(),i.getProductId(),i.getQuantity(),"SALES_ORDER",o.getId(),"Confirm "+o.getCode());o.setStatus("COMPLETED");o.setConfirmedAt(Instant.now());if(o.getDebtAmount().signum()>0){Customer c=customers.findByIdAndTenantIdAndDeletedAtIsNull(o.getCustomerId(),t).orElseThrow();debts.save(CustomerDebtTransaction.builder().tenantId(t).customerId(c.getId()).sourceType("SALES_ORDER").sourceId(o.getId()).direction("INCREASE").amount(o.getDebtAmount()).remainingAmount(o.getDebtAmount()).dueDate(LocalDate.now().plusDays(c.getPaymentTermDays())).note(o.getCode()).createdBy(TenantContext.userOrZero()).build());}audit.log("SALES_ORDER_CONFIRMED","SalesOrder",o.getId(),o.getCode());notifications.publish(t,"SALES_ORDER_CONFIRMED","Đơn đã xác nhận","Đơn "+o.getCode()+" đã xác nhận");return ApiResponse.ok(o);}
 @PostMapping("/{id}/cancel") @PreAuthorize("hasAuthority('SALES_ORDER_CONFIRM')") @Transactional @CacheEvict(value="dashboard",allEntries=true) ApiResponse<?> cancel(@PathVariable Long id){Long t=TenantContext.tenantRequired();SalesOrder o=orders.findByIdAndTenantId(id,t).orElseThrow(()->new BusinessException("Order not found"));if(!"DRAFT".equals(o.getStatus()))throw new BusinessException("Only DRAFT can be cancelled");o.setStatus("CANCELLED");audit.log("SALES_ORDER_CANCELLED","SalesOrder",o.getId(),o.getCode());notifications.publish(t,"SALES_ORDER_CANCELLED","Don da huy","Don "+o.getCode()+" da huy");return ApiResponse.ok(o);}
}
