create table tenants(id bigserial primary key,name varchar(255),active boolean);
create table permissions(id bigserial primary key,name varchar(100) unique);
create table roles(id bigserial primary key,name varchar(100) unique);
create table role_permissions(role_id bigint references roles(id),permission_id bigint references permissions(id),primary key(role_id,permission_id));
create table app_users(id bigserial primary key,username varchar(100) unique,password_hash varchar(255),full_name varchar(255),tenant_id bigint,active boolean);
create table user_roles(user_id bigint references app_users(id),role_id bigint references roles(id),primary key(user_id,role_id));
create table products(id bigserial primary key,tenant_id bigint,name varchar(255),sku varchar(100),barcode varchar(100),cost_price numeric(19,2),selling_price numeric(19,2),min_stock int,active boolean,deleted_at timestamp);
create table customers(id bigserial primary key,tenant_id bigint,name varchar(255),phone varchar(50),address varchar(500),credit_limit numeric(19,2),payment_term_days int,active boolean,deleted_at timestamp);
create table warehouses(id bigserial primary key,tenant_id bigint,name varchar(255));
create table stock_items(id bigserial primary key,tenant_id bigint,warehouse_id bigint,product_id bigint,quantity_on_hand int,version bigint,unique(tenant_id,warehouse_id,product_id));
create table inventory_transactions(id bigserial primary key,tenant_id bigint,warehouse_id bigint,product_id bigint,source_type varchar(50),source_id bigint,direction varchar(20),quantity int,before_quantity int,after_quantity int,note varchar(500),created_by bigint,created_at timestamp);
create table sales_orders(id bigserial primary key,tenant_id bigint,customer_id bigint,warehouse_id bigint,code varchar(100) unique,status varchar(30),total_amount numeric(19,2),paid_amount numeric(19,2),debt_amount numeric(19,2),created_at timestamp,confirmed_at timestamp);
create table sales_order_items(id bigserial primary key,sales_order_id bigint references sales_orders(id),product_id bigint,quantity int,unit_price numeric(19,2),discount_amount numeric(19,2),line_total numeric(19,2));
create table customer_debt_transactions(id bigserial primary key,tenant_id bigint,customer_id bigint,source_type varchar(50),source_id bigint,direction varchar(20),amount numeric(19,2),remaining_amount numeric(19,2),due_date date,note varchar(500),created_by bigint,created_at timestamp);
create table payments(id bigserial primary key,tenant_id bigint,customer_id bigint,amount numeric(19,2),note varchar(500),created_by bigint,created_at timestamp);
create table audit_logs(id bigserial primary key,tenant_id bigint,actor_id bigint,action varchar(100),entity_type varchar(100),entity_id bigint,new_value text,created_at timestamp);
create table notifications(id bigserial primary key,tenant_id bigint,type varchar(100),title varchar(255),message text,read_flag boolean,created_at timestamp);
create index idx_products_tenant on products(tenant_id,deleted_at,name);
create index idx_customers_tenant on customers(tenant_id,deleted_at,name);
create index idx_stock_key on stock_items(tenant_id,warehouse_id,product_id);
create index idx_sales_tenant on sales_orders(tenant_id,status);
create index idx_debt_customer on customer_debt_transactions(tenant_id,customer_id,direction,remaining_amount);
