import type { TFunction } from 'i18next';
import type { InventoryTransaction } from '../features/inventory/types/inventory.types';

export function inventorySourceLabel(sourceType: string | null | undefined, t: TFunction) {
  if (!sourceType) {
    return t('inventory.sourceType.UNKNOWN');
  }

  return t(`inventory.sourceType.${sourceType}`, {
    defaultValue: t('inventory.sourceType.UNKNOWN'),
  });
}

export function inventoryDirectionLabel(direction: string | null | undefined, t: TFunction) {
  if (!direction) {
    return t('inventory.direction.UNKNOWN');
  }

  return t(`inventory.direction.${direction}`, {
    defaultValue: t('inventory.direction.UNKNOWN'),
  });
}

/**
 * Localize only notes that are generated by DMS itself.
 * Notes entered by staff during manual receipts/payments must remain exactly as entered.
 */
export function inventoryNoteLabel(
  transaction: Pick<InventoryTransaction, 'sourceType' | 'note'>,
  t: TFunction,
) {
  const note = transaction.note?.trim();
  if (!note) {
    return '--';
  }

  if (transaction.sourceType === 'ADJUSTMENT' && note === 'Seed stock') {
    return t('inventory.systemNote.seedStock');
  }

  if (transaction.sourceType === 'SALES_ORDER') {
    const confirmedOrder = note.match(/^Confirm\s+(.+)$/i);
    if (confirmedOrder) {
      return t('inventory.systemNote.salesOrderFulfilled', { code: confirmedOrder[1] });
    }
  }

  return transaction.note ?? '--';
}
