export const queryKeys = {
  auth: ['auth'] as const,
  products: ['products'] as const,
  productRows: ['products', 'rows'] as const,
  customers: ['customers'] as const,
  customer: (customerId: number | string) => ['customers', customerId] as const,
  customerDebt: (customerId: number | string) => ['customers', customerId, 'debt'] as const,
  salesOrders: ['sales-orders'] as const,
  salesReportRoot: ['reports', 'sales'] as const,
  salesReport: (from: string | null, to: string | null) => ['reports', 'sales', { from, to }] as const,
  salesOrderDetail: (orderId: number | string) => ['sales-orders', orderId, 'detail'] as const,
  invoicesRoot: ['invoices'] as const,
  invoices: (page: number) => ['invoices', { page }] as const,
  invoice: (invoiceId: number | string) => ['invoices', invoiceId] as const,
  inventoryDefaultWarehouse: ['inventory', 'default-warehouse'] as const,
  inventoryStock: ['inventory', 'stock'] as const,
  inventoryHistory: ['inventory', 'history'] as const,
  dashboard: ['reports', 'dashboard'] as const,
  auditLogs: ['audit-logs'] as const,
  notifications: ['notifications'] as const,
  teamMembers: ['team', 'members'] as const,
  teamRoles: ['team', 'roles'] as const,
  teamPermissions: ['team', 'permissions'] as const,
  helpHistory: ['help', 'history'] as const,
  helpHistoryList: (params: object) => ['help', 'history', params] as const,
};
